# Generated by Django 4.2.20 on 2025-04-04 04:03

from django.db import migrations, models
import users.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=users.storage_backends.MediaStorage(), upload_to='users_image/'),
        ),
    ]
