version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn store.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - store/store/.env

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - store/store/.env

  redis:
    image: redis:7
    restart: always

  celery:
    build: .
    command: celery -A store worker --loglevel=info
    depends_on:
      - redis
      - web
    env_file:
      - store/store/.env

  celery-beat:
    build: .
    command: celery -A store beat --loglevel=info
    depends_on:
      - redis
      - web
    env_file:
      - store/store/.env

volumes:
  postgres_data: