# Generated by Django 4.2.20 on 2025-04-22 06:06

from django.db import migrations, models
import users.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_basket_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=users.storage_backends.MediaStorage(), upload_to='products_images'),
        ),
    ]
